global:
route:
  receiver: 'slack'
  group_by: ['alertname']
  group_wait: 10s
  receiver: 'slack'
  group_interval: 15s

receivers:
- name: 'slack'
  slack_configs:
  - channel: "#haytham-turkey"
    send_resolved: true
    api_url: 'https://hooks.slack.com/services/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'
